http_port 3128

visible_hostname dsh-egress-proxy

# Không cần ICMP pinger trong container
pinger_enable off

# -------------------------------------
# Allowed ports
# -------------------------------------

acl SSL_ports port 443
acl Safe_ports port 80
acl Safe_ports port 443

acl CONNECT method CONNECT

# -------------------------------------
# Domain whitelist
# -------------------------------------

acl allowed_domains dstdomain "/etc/squid/allow-domains.txt"

# -------------------------------------
# Security
# -------------------------------------

http_access deny !Safe_ports

http_access deny CONNECT !SSL_ports

# ONLY domains configured above
http_access allow allowed_domains

# Everything else blocked
http_access deny all

# -------------------------------------
# Privacy
# -------------------------------------

forwarded_for delete
via off
request_header_access X-Forwarded-For deny all
request_header_access Via deny all

# -------------------------------------
# Logging
# -------------------------------------

access_log stdio:/var/log/squid/access.log